jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Configure Git user
      run: |
        git config --global user.email "toniabondar31@gmail.com"
        git config --global user.name "a42b"

    - name: Deploy to GitHub Pages
      run: npm run deploy
