name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Upload code to server
      run: |
        echo "$SSH_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        scp -i deploy_key.pem -r . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/mood-music-app

    - name: Deploy on server
      run: |
        ssh -i deploy_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /var/www/mood-music-app
        npm install
        npm run build
        pm2 restart all || pm2 start server.js
        EOF
